DROP TABLE IF EXISTS "tbl_department";
CREATE TABLE "tbl_department" ("name" CHAR PRIMARY KEY  NOT NULL , "info" CHAR, "imgpath" CHAR, location CHAR);
INSERT INTO "tbl_department" VALUES('Department of Computer Studies','\tThe Department of Computer Studies is the 20th department of the University of Yangon. Established in 2004 the Department aims to upgrade the knowledge of ICT in the country, to nurture new and young software and network engineers, promote researches in ICT field, train and build up a large pool of qualified personnel in the ICT field.\n\n\tThe Department offers Master of Science degree in Computer Science, and Post-graduate Diploma in Computer Science (PDCS). The students at this Department are graduate students who had acquired heir first degree in various fields already. As the Department''s focus is on producing computer professionals, the classrooms are fully equipped with computers, LCD projectors plus state- of-the-art AV accessories for a hands-on training of the students. The Department has a fully air-conditioned and modern Resource Centre providing the students with internet access also.\n\n\tUnder arrangement from Human Resources Department of Yangon University of Ministry of Education, M.Sc (Computer Science) was launched online in August 2004 by Department of Computer Studies. In April 2005, DCS (Diploma in Computer Science) has been implementing to extend the online education.\n\n\tIn December 2009, WBTS Online Teaching System got MCPA Excellent Award for 2008 which is awarded by Myanmar Computer Professional Association (MCPA).','cs','University Lab Building');
INSERT INTO "tbl_department" VALUES('Department of Zoology','\tThe Department of Zoology was established in 1955. The Department offers post graduate courses to students studying for further degrees leading to Master of Science and Master of Research degrees. The doctoral programme is also in place and currently there are 33 Ph.D degree holders. The Department maintains a library, a museum and three modern laboratories. A small butterfly house is now in operation with the Professor of Zoology heading a team of dedicated researchers from the Department.\n\n\t

The Department has signed MOUs with a number of international NGOs and is conducting periodic fauna surveys together with these institutions. The Zoology Department is currently doing researches in Systematics, Ecological studies, Behavourial studies, Environmental studies, Bio-diversity conservation, Biotechnology, Parasitology, Entomology, Ichthyology, Orinthology, Mammology.\n\n\t

Department members has also attended and read papers on the various fields of zoology at a number of international forums and seminars. The Zoology Department has also published, in collaboration with the Harrison Institute of United Kingdom, a booklet describing the country''s varied flora and fauna, its people and culture. This has led to increased awareness of Myanmar''s unique position in the world''s action for conservation among the international scientific community as well as the general public\n\n\t','zoo','Science Building');
INSERT INTO "tbl_department" VALUES('Department of Physics','\tThe Department of Physics came into existence together with Yangon University in 1920. The Department aims to teach and also investigate all the aspects of physics as related to human existence and his environment and the best ways to harness the forces of nature for its benefit and also to produce future physicists of high caliber.\n\n\t

With over 100 academic staffs, many with high and accomplished academic and professional qualifications in their respective fields of expertise, the Physics Department offers Master of Science (Physics/ Engineering Physics), Master of Research and Doctor of Philosophy (Ph.D) in many related fields. The doctoral programme was instated in 1994 and to date the Department has been produced on the average some ten PhDs per academic year.\n\n\t

Most notably the Physics Department has also produced PhD degree holders in Information Technology. The Department of Physics is one of the most successful departments of Yangon University with high student''s interest in the courses it offers under the HRD programme leading to the 4-year Bachelor of Science (Engineering) degrees in IT and Electronics. Under this programme the Physics Department offers Diploma in Electronics, Diploma in Information Techno-logy, Bachelor of Science in Engineering (IT)an~ Bachelor of Science in Engineering (Electronics). A two-yea r post-graduate Diploma in Applied Physics and Master of Science in Engineering Physics, Master of Science in Physics are also offered. The Physics Department also has fully equipped modern laboratories, both for research and post-graduate teaching purposes.
','physic','Science Building');
INSERT INTO "tbl_department" VALUES('Department of Philosophy','\tThe Department was established in 1920 and offers a wide selection of courses covering both traditional and contemporary schools of thought. The curriculum is well organized to help students acquire the necessary skills of reading and comprehension, conceptual analysis and argumentation. The Philosophy Department offers courses leading to Master of Arts, Master of Research and Doctor of Philosophy (Ph.D) in Philosophy.\n\n\tThe doctoral programme was instituted in 1998 and currently there are 6 Ph.D holders and more than 40 candidates doing researches for their dissertations on Philosophy of Culture.\n\n\tThe Department has nine fulltime teaching staff and two retired Professors are acting as Professors Emeritus. The academic staffs are required to do both teaching and research as part of their academic responsibilities. The Department holds monthly paper reading sessions and present papers on Philosophy at the annual University Paper Reading Sessions. The Department takes keen and active research interest in both Myanmar culture and thinking and in other Eastern and Western philosophical thoughts and developments. The Department maintains an in-house library for both the staff and researchers.','philo','Yamanya Hall');
INSERT INTO "tbl_department" VALUES('Department of Psychology','\tDuring the early years the Department of Psychology was part of the Department of Philosophy but emerged as a separate Department of Psychology in 1952. The Psychology Department''s objectives are to acquire an in-depth knowledge of what psychology is and to acquire a set of general personal transferable skills and capabilities to set the student on the road to a lifetime of independent development.\n\n\tThe Department has well-qualified academic staff with good teaching background and research interests -and offers courses leading to Master of Arts, Master of Research and Doctor of Philosophy (Ph.D) in Psychology. The Department of Psychology also conducts researches on its own and also in collaboration with the UN agencies, local NGOs and other government ministries and departments. There is a small but adequate departmental library and psychological laboratory for the staff and researchers.','psycho','Yamanya Hall');
INSERT INTO "tbl_department" VALUES('Department of Myanmar','\tThe Department of Myanmar Established in 1941. Currently the Department offers courses leading to Master of Arts, Master of Research and Doctor of Philosophy(Ph.D) in the Myanmar language and literature. The Department offers courses on studies of ancient Myanmar languages, contemporary Myanmar language, General Linguistics and Phonetics, Sociolinguistics, Semantics and Stylistics plus studies on ancient and contemporary Myanmar literature.\n\n\tIn addition to their teaching duties, the teaching staff of the Department also engages in researches on various aspects of the Myanmar language and conduct multidisciplinary course on Myanmar studies. The Department of Myanmar is also an active participant in various socio-educational activities of the University.','myan','Taungu Hall');
INSERT INTO "tbl_department" VALUES('Department of Mathematics','\tThis Department was also created together with YangonUniversity in 1920. There are 81 staff members in the Department.The Department offers Masterof Science, Master of Research and Ph.D degrees.\n\n\tThe Mathematics Departmentstarted the doctoral programmein 1994 and there are now 13Ph.D degree holders inMathematics awarded by the Department.\n\n\tThe Mathematics Department also offers courses leading to Master, Master of Research and Doctor ofPhilosophy(Ph.D) degrees inmathematical science.The Mathematics Departmentis also actively associated withthe HRD programme andconducts courses on EngineeringMathematics leading to aBachelor of Science in Engineering{B.5c (Engg)} as well ascertificate and diploma courseson applied and advancedcomputing. The Mathematics Department is currently engaged in such fields as Applied Mathematics, Functional Analysis, Partial Differential Equations, Computational Mathematics, Statistics and Probability Theory, Algebraic Topology, DiscreteMathematics and Graph Theory.','math','Science Building');
INSERT INTO "tbl_department" VALUES('Department of Library and Information Studies','\tThe Department of Library and Information Studies came into existence on part-time basis from June 1971 to 1997. At that time, the Department‘s name was Library Science. U Thaw Kaung, Chief Librarian of the Universities’ Central Library, served as Head of the part –time department for more than two and a half decades. The Department has produced over 300 post-graduate diploma holders who are now serving in various local and international libraries. In 1997, it was re-structured as the 19th department of the University under the new name, “Library and Information Studies”. Then, it was headed by Professor U Thein Lwin from 1997 to 2007. U Thein Shwe became Head of Department from 2007 to 2011. At present, Daw Htay Htay Win (Lecturer) acts as Head of Department. The Department has thirteen Faculty staffs and two office staffs.\n\n\tThe Department has carried out other activities related to library. It has coordinated with various departments and the Myanmar Library Association (MLA) by conducting frequent short-term training of basic library educational programmes on request since 1992 to date. Moreover, It actively participated in the University’s social, cultural, religious and educational activities such as cultural shows, book-shows, sports events and festive ceremonies.','librarystudies','Mandalay Hall');
INSERT INTO "tbl_department" VALUES('Department of Law','\tThe Department of Law came into existence in 1920 together with the Rangoon University, what is today the University of Yangon (YU). It was one of seven original affiliated faculties of the Rangoon University. During the early years, the Law Department only offered a law degree known as Bachelor of Laws (BL) degree as a part-time post graduate degree course. The BL Degree consisted of a two year course of study.\n\n\tWith advent of the Revolutionary Council after 1962, a Committee to reform legal education was established, and significant reforms were accomplished by the Higher Education Law, 1964. After 1964, it became a fulltime course. Under this system, students obtained BA (Law) degree after 4 years of study and had to continue their studies another one year for LLB degree.\n\n\tNew system of higher education brought the fulltime legal education course in the name of LLB degree in 1965. It became a five year, full-time course of study at the Department of Law.\n\n\tThe Bachelor of Laws degree program still remains the main vehicle for University legal studies at all Law Departments of Universities except University of Yangon and University of Mandalay. Today the YU Department of Law is exclusively devoted to postgraduate legal studies.\n\n\tThe first postgraduate legal degree program at the Department of Law, the LLM degree program, was established in 1973. The new LLM program presently run is two years in duration.  The program offers the opportunity to specialize in four different areas: Civil Law, Commercial Law, International Law, and Maritime Law.  Since 1999, the Department of Law has offered PhD degree program which has consistently been in high demand. As part of the University’s Human Resources Development Program, graduate diploma courses in Business Law, International Law, and Maritime Law are offered by the Department of Law under the University’s Human Resources Development Program since 2004.','law','Yamanya Hall');
INSERT INTO "tbl_department" VALUES('Department of International Relationship','\tThis is a relatively new department as it was established only in 1984. There are 28 teaching staffs at the Department for 2013-2014 academic year. The Department offers courses leading to Diploma in International Relations, Master of Arts, Master of Research and Doctor of Philosophy (Ph.D) degree. The studies cover governmental systems and politics, major political, economic, environmental and social issues in international relations around the world.\n\n\tThe Master of Arts in International Relations is open to all Bachelor of Arts (Honours) in International Relations degree holders who are eligible to proceed Master classes.','ir','Waitharli Hall');
INSERT INTO "tbl_department" VALUES('Department of Industrial Chemistry','\tTeaching of Industrial Chemistry was introduced at the Yangon University Chemistry Department in November 1966. A separate Department of Industrial Chemistry, however, cameinto existence in 1986. The objective of the Department of Industrial Chemistry is to promote and apply the acquired knowledge of the physical and chemical sciences to the widerange of production and processingindustries for the benefit of mankind and also matters relating to conservation of the environment from the effects of development of economy and technical advance','ic','University Lab Building');
INSERT INTO "tbl_department" VALUES('Department of History','\tEstablished in 1920 the Department has been associated with the founding of Yangon University ever since. The History Department aimsto produce graduates and newgenerations of historians who can establish human relationships that are in harmony and confident for the development of the country. For these aims and objectives the History Department offers courses leading to Master of Arts, Master of Research and Doctor of Philosophy (Ph.D) in history. Master degree in History candidates are required to attend a two years full time course and to successfully pass the examinations held at the end of each semester.','history','Waitharli Hall');
INSERT INTO "tbl_department" VALUES('Department of Geology','\tThe Department of Geography and Geology was created in 1923. But in 1948 they were separated and the Department of Geology came into existence. Currently there are 16 academic staffmembersat the Department. The aim of the academic programme of the Department of Geology is to offer a comprehensive range of degrees to suit the varied aims and academic backgrounds of the students.','geology','Mandalay Hall');
INSERT INTO "tbl_department" VALUES('Department of Geography','\tGeography Department was set up in 1924. Geography Department aims to disseminate geographic knowledge among the public; to effectively assist with geographic knowledge in national development endeavours; and to enhance the collaborations in research and teaching with international universities and organizations.\n\n\tCurrently, the department has a total of thirty- five staffs; thirty teaching staffs and five office staffs headed by the Professor. The academic staffs do both teaching and field researches as part of their academic duties. Two Professors, two Associate Professors, twenty-one lecturers, three Assistant lecturers and two tutors served for the Geography Department.','geography','Art Hall');
INSERT INTO "tbl_department" VALUES('Department of English','\tThe English Department dates back to 1920, the year when Yangon University became separatedfrom Calcutta (Kolkota) University. There are 33 Tutors, Asst. Lecturers, Lecturers, Associate Professors and Professors in the Department. Currently the English Department offers diploma and postgraduate courses on English up to an including Master of Arts, Master of Research and Ph.D degrees for students of English.\n\n\tMany of these courses are full time courses and the mode of instruction is through lectures, self-study, discussions, paper presentations, written assignments and seminars. The student''s progress is measured on the individual''s active participation in discussions, paper presentations and seminars. However, assessments on written assignments and written examinations at the end of each semester are the main determinants for the conferment of Diploma and Master degrees.','english','Marlar Hall');
INSERT INTO "tbl_department" VALUES('Department of Chemistry','\tThe Department of Chemistry was founded in 1880 and incorporated into the newly founded University of Yangon in 1920. It is therefore one of the oldest departments of the University.The vision of the Department is to create a system that can build a body of knowledge power house which enhances national prosperity and competitive standing in the world of work. It is currently constituted by 85 academic staff, 7 administrative staff and 20 laboratory technicians.\n\n\tThe Department offers B.Sc. (Hons.), Master and Mater of Research Degrees in two main branches - Chemistry and Biochemistry, and PhD Degree in Chemistry. These degrees are awarded based on the five specialized fields of Chemistry which are Organic Chemistry, Inorganic Chemistry, Physical Chemistry, Analytical Chemistry and Nuclear Chemistry.  Master programme of the Department was approved and officially started since 1924.  Doctoral degree programme began in 1994.  The Department offered 442 PhD graduates in Chemistry from 1997 - 2012.  From 2012-2013 academic year, it re-opened the BSc (Hons) degree courses in Chemistry and Biochemistry.\n\n\tThe mission of the department is to promote theoretically sound and intellectually matured researchers through advanced chemical education and research programmes with the following objectives:\n\n\t-To upgrade the chemistry curriculum and syllabi for undergraduate, master  and doctoral degree courses to international level\n\t-To set up a fully modernized spectroscopic laboratory\n\t-To arrange academic staff exchange programme with international universities\n\t-To produce high quality graduates\n\t-To continuously develop the academic and support staff to meet the aspirations\n\t-To be a centre of excellence\n\t-To generate new young blood qualified researchers who are intellectually matured and skilled developed (Technocrats)\n\n\tThe Department of Chemistry operates under close supervision of Professor Head who is assisted by the professors taking decisions in association with the departmental board The Board which comprises a cross section of the academic staff of the department and the work of the board is carried out by nine Panels comprising five professors and four associate professors and some senior lecturers are included in the board. The Department Head sits as a chairperson and the panels meet as and when necessary.','chemistry','Science Building');
INSERT INTO "tbl_department" VALUES('Department of Botany','\tThe Botany Department sets its objectives to conduct academic and research programmes concerning plant sciences. These objectives are development of efficient and effective human resources, improvement of post graduate or doctoral programmes, improvement of botanical sciences programmes, high standard of learning and high quality research. The Department has 80 staff members and offers courses leading to Master of Science, Master of Research and Doctorof Philosophy in Botany.\n\n\tThe Department of Botany awarded its first doctorate degree in 2001 .A new interdisciplinary Master of Science course was introduced to take the leading role in teaching of environmental studies. The staffs of the Department also actively participate in lectures and practical demonstrations for Master students of the biotechnology, biochemistry and environmental studies courses. Under the CHRD programme the Botany Department also conducts lectures on environmental studies leading to a Bachelor of Engineering (B.Sc Eng) degree. The Department has signed many MOUs with international NGOs. The academic staffs of the Department are active in field researches and participates ininternational seminars and workshops. They also collaborate with international scientists in many botanical surveys inside the country. The Botany Department has well-equipped laboratories as well as a reference library and a herbarium.','botany','Science Building');
INSERT INTO "tbl_department" VALUES('Department of Archaeology','\tThe Department was set up in 1994 with the aim to promote awareness of ancient Myanmar culture, and archaeological knowledge, to train new generations of archaeologists and to support tourism sector in Myanmar. Post-graduate Diploma, Master of Arts, Master of Research and Doctor of Philosophy on Archaeology courses are offered.\n\n\tElective Courses offered by the Department include Archaeology of Myanmar, Prehistoric Archaeology , Proto-historic and early Historical Archaeology , Archaeology of mainland\n\n\tSoutheast Asia, Indian , Chinese and  Ceramic Archaeology, preservation of Monuments, Protection of National Cultural Properties and Dating Archaeological Evidences.\n\n\tThe ongoing research programmes include study on excavated findings from the old Bagan Palace and Beikthano sites, and stone implements found at Htauk-ma-gone in Salingyi Township. Excavations undertaken by the Department are sites in Sriksetra and the continuing investigations into skeletal remains found in Nyaung Gan village, Budalin Township. Students have also conducted study tours around various archaeological sites in the country. Moreover, quarterly paper reading and presentations sessions are held to disseminate the knowledge among faculty members and students. There are twelve academic staffs at the Department. The Department of Archaeology has planned to open the CHRD class, Postgraduate Certificate in culture of Bagan.It is short term course for three months','archaeology','Waitharli Hall');
INSERT INTO "tbl_department" VALUES('Department of Anthropology','\tThe Anthropology Department was established in 1950 under the  guidance of the Rector of the University, Dr. Htin Aung. The Department offers courses for Master of Arts, Master of Research and Diploma. Besides, it holds weekly seminars, paper presentations and group discussions  to  further anthropological knowledge. The Department has also been conducting many research projects on national groups and community development in Myanmar.\n\n\tSince 1997, the ethnographic studies on national groups including Akha, Wa, Kokant, Salone, Naga, Kayang (Padaung), Chin, Maramargyi and Tarone have been conducting. Recently, the Department has carried out applied anthropological research project on the impact of tourism in Inlay Lake Region with international researchers. The main goal of the Department is to advance knowledge of evolution, changes and progress of human beings.
','anthropology','Science Building');
INSERT INTO "tbl_department" VALUES('Department of Oriental Studies','\tThis is one of the oldest Departments of the University as it came into existence together with the University in 1920.There are Tutors, AssistantLecturers, Lecturers, and a Professor in the Department. Three part-time Professors andthree Venerable Sayadaws from the International Theravada Buddhist Missionary University and one Venerable Sayadaw from the State Pariyatti Sasana University are acting as part time Lecturers.\n\n\tThe Department offers courses leading to the degree of Master of Arts, Master of Research and Doctor of Philosophy (Ph.D) in Oriental Studies.\n\n\tThe Doctoral programme was introduced in 1999 and currentlythere are 44 candidates doing research in the field of Pali literature and other allied subjects. Another batch of seven students is attending the one-year preliminary course before doing their dissertations. There are 24 teaching staffs in the Department and there is an in-house library for the staff and researchers. The teaching staffs are also tasked to do researches of academic anddevelopmental nature. The Department of Oriental Studies also offers a 9-month Diploma Course known as Diploma for Oriental Studies (DOS) under the Yangon University Centre for Human Resource Development.','os','Art Hall');
DROP TABLE IF EXISTS "tbl_marker";
CREATE TABLE "tbl_marker" ("title" CHAR PRIMARY KEY  NOT NULL , "latitude" DOUBLE, "longitude" DOUBLE, "icon" CHAR);
INSERT INTO "tbl_marker" VALUES('Mandalay Hall',16.827195,96.13356,'apartment');
INSERT INTO "tbl_marker" VALUES('Taungu Hall',16.827968,96.132756,'apartment');
INSERT INTO "tbl_marker" VALUES('Waitharli Hall',16.828222,96.132131,'apartment');
INSERT INTO "tbl_marker" VALUES('Dagon Hall',16.828849,96.133458,'hostel');
INSERT INTO "tbl_marker" VALUES('Judson Church',16.830813,96.134134,'church');
INSERT INTO "tbl_marker" VALUES('Universities Central Library',16.830904,96.135903,'library');
INSERT INTO "tbl_marker" VALUES('Convocation Hall',16.833325,96.136185,'conference');
INSERT INTO "tbl_marker" VALUES('Science Building',16.831756,96.1366,'apartment');
INSERT INTO "tbl_marker" VALUES('Art Hall',16.832321,96.134964,'conference');
INSERT INTO "tbl_marker" VALUES('Science Canteen',16.830302,96.136683,'cafetaria');
INSERT INTO "tbl_marker" VALUES('Taungu Canteen',16.828096,96.133622,'cafetaria');
INSERT INTO "tbl_marker" VALUES('University Lab Building',16.828198,96.137265,'apartment');
INSERT INTO "tbl_marker" VALUES('Marlar Hall',16.83247,96.133724,'apartment');
INSERT INTO "tbl_marker" VALUES('Yamanya Hall',16.827683,96.131675,'apartment');
INSERT INTO "tbl_marker" VALUES('ShweBo Hall',16.830055,96.133877,'hostel');
INSERT INTO "tbl_marker" VALUES('Amara Hall',16.826956,96.132465,'apartment');
INSERT INTO "tbl_marker" VALUES('Thiri Hall',16.831623,96.133352,'apartment');
INSERT INTO "tbl_marker" VALUES('Recreation Centre',16.831216,96.135025,'group');
INSERT INTO "tbl_marker" VALUES('Thit Pote',16.83222,96.135948,'tree');
INSERT INTO "tbl_marker" VALUES('Innyar Hall',16.830161,96.138593,'hostel');
INSERT INTO "tbl_marker" VALUES('Yadanar Hall',16.831306,96.138308,'hostel');
INSERT INTO "tbl_marker" VALUES('Innwa Hall',16.829663,96.13642,'hostel');
INSERT INTO "tbl_marker" VALUES('SagaingHall',16.829571,96.135728,'hostel');
INSERT INTO "tbl_marker" VALUES('Pinya Hall',16.828975,96.135379,'hostel');
INSERT INTO "tbl_marker" VALUES('Bago Hall',16.828215,96.135235,'hostel');
INSERT INTO "tbl_marker" VALUES('Thahton Hall',16.827717,96.135771,'hostel');
INSERT INTO "tbl_marker" VALUES('UY Canteen',16.833132,96.137027,'cafetaria');
INSERT INTO "tbl_marker" VALUES('Art Canteen',16.833047,96.134277,'cafetaria');
